---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/alpine-ci-tools
    tag: v0.0.7

inputs:
  - name: pipeline
  - name: config

outputs:
  - name: output
  - name: config-mod

run:
  path: pipeline/ci/scripts/certs/redeploy-all.sh
