---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/ci-tools
    tag: edge

params:
  OM_SKIP_SSL_VALIDATION: false

inputs:
  - name: pipeline
  - name: config

run:
  path: pipeline/ci/scripts/enable-ldap.sh
