---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/ci-tools
    tag: edge

params:
  OM_TARGET:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_SKIP_SSL_VALIDATION: false
  OM_TRACE: false

inputs:
  - name: pipeline
  - name: config

run:
  path: pipeline/ci/scripts/enable-ldap.sh
