---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/alpine-ci-tools
    tag: edge

inputs:
  - name: pipeline
  - name: config

run:
  path: pipeline/ci/scripts/rotate-non-configurable-leaf-certs.sh
