---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/ci-tools
    version: v0.1.6

inputs:
  - name: pipeline

run:
  path: pipeline/ci/scripts/update-certificates.sh
